name: e2e pipeline - cypress github actions

on:
  push:
  pull_request:
    branches: [master, dev]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        run: yarn

      - name: test
        run: |
          sudo apt-get install ffmpeg x11grab
          npm install screencap -g
          screencap 90 screen_capture.mp4 &

      - name: Run e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: yarn test:e2e:local
          browser: chrome
          spec: tests/e2e/specs/*
          headed: true

      - name: Archive e2e artifacts
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # pin@v2
        if: always()
        with:
          name: e2e-artifacts
          path: |
            tests/e2e/videos
            tests/e2e/screenshots
            screen_capture.mp4
        continue-on-error: true
